(cl:defpackage hw2-srv
  (:use )
  (:export
   "ADDTWOIINTS"
   "<ADDTWOIINTS-REQUEST>"
   "ADDTWOIINTS-REQUEST"
   "<ADDTWOIINTS-RESPONSE>"
   "ADDTWOIINTS-RESPONSE"
   "DOESNOTHING"
   "<DOESNOTHING-REQUEST>"
   "DOESNOTHING-REQUEST"
   "<DOESNOTHING-RESPONSE>"
   "DOESNOTHING-RESPONSE"
  ))

