// Generated by gencpp from file hw2/DoesNothing.msg
// DO NOT EDIT!


#ifndef HW2_MESSAGE_DOESNOTHING_H
#define HW2_MESSAGE_DOESNOTHING_H

#include <ros/service_traits.h>


#include <hw2/DoesNothingRequest.h>
#include <hw2/DoesNothingResponse.h>


namespace hw2
{

struct DoesNothing
{

typedef DoesNothingRequest Request;
typedef DoesNothingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DoesNothing
} // namespace hw2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw2::DoesNothing > {
  static const char* value()
  {
    return "f16097f93022db785b2cc9436c158893";
  }

  static const char* value(const ::hw2::DoesNothing&) { return value(); }
};

template<>
struct DataType< ::hw2::DoesNothing > {
  static const char* value()
  {
    return "hw2/DoesNothing";
  }

  static const char* value(const ::hw2::DoesNothing&) { return value(); }
};


// service_traits::MD5Sum< ::hw2::DoesNothingRequest> should match 
// service_traits::MD5Sum< ::hw2::DoesNothing > 
template<>
struct MD5Sum< ::hw2::DoesNothingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::DoesNothing >::value();
  }
  static const char* value(const ::hw2::DoesNothingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::DoesNothingRequest> should match 
// service_traits::DataType< ::hw2::DoesNothing > 
template<>
struct DataType< ::hw2::DoesNothingRequest>
{
  static const char* value()
  {
    return DataType< ::hw2::DoesNothing >::value();
  }
  static const char* value(const ::hw2::DoesNothingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw2::DoesNothingResponse> should match 
// service_traits::MD5Sum< ::hw2::DoesNothing > 
template<>
struct MD5Sum< ::hw2::DoesNothingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw2::DoesNothing >::value();
  }
  static const char* value(const ::hw2::DoesNothingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw2::DoesNothingResponse> should match 
// service_traits::DataType< ::hw2::DoesNothing > 
template<>
struct DataType< ::hw2::DoesNothingResponse>
{
  static const char* value()
  {
    return DataType< ::hw2::DoesNothing >::value();
  }
  static const char* value(const ::hw2::DoesNothingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW2_MESSAGE_DOESNOTHING_H
